use std::fs;
use std::path::PathBuf;

use jumbo_build::cli::Cli;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("docs")
        .join("cli-reference.md");
    let generated = clap_markdown::help_markdown::<Cli>();
    let contents = format!(
        "<!-- Generated by `cargo run --example generate-cli-docs`; do not edit manually. -->\n\n{generated}"
    );

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output_path, contents)?;
    println!("Generated {}", output_path.display());

    Ok(())
}
